spring.application.name=furnitureStore
spring.datasource.url=jdbc:mysql://localhost:3306/furniture_store
spring.datasource.username=root
spring.datasource.password=root

spring.security.user.name = username
spring.security.user.password = password